version: '3'

services:
  app-php:
    container_name: app-api
    build:
      context: ./
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=root
      - DB_USER=root
      - DB_PASS=root
      - DB_PORT=3306
      - DB_DRIVER=mysql
      - DB_CHARSET=utf8
      - DB_ENGINE=InnoDB
      - APP_KEY=base64:Y9Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7A=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000

  database:
    container_name: mariadb
    env_file:
      - ./.env
    image: mariadb:10.9
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=root
    volumes: # CHANGE THE LOCAL VOLUME PATH TO YOUR OWN
      - C:\Users\itoga\Desktop\db-calendar:/var/lib/mysql
    logging:
      driver: none

volumes:
  rosieres-calendar:
    driver: local
